# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: spider
release:
  github:
    owner: fitzix
    name: spider
  prerelease: auto
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: zip
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true